export const QUESTIONS = [
  'Why do you think you are a good fit for this particular project?',
  'Do you have suggestions to make this project run successfully?',
  'Why did you apply to this particular job post?',
  'Do you know/work with Figma?',
  'What questions do you have about the project/job post?',
  'What part of this project most appeals to you?',
  'Which challenging part of this job post you are most experienced at?',
  'Which of the required job skills do you feel you are strongest at?',
  'What past project or job have you had that is most like this one and why?',
  'Which part of this project do you think will take the most time?',
  'Where do you get inspiration from?',
  'What frameworks have you worked with?',
  'Please list any certifications related to this project',
  'Describe your recent experience with similar projects',
  'Include a link to your GitHub profile and/or website',
  'Describe your approach to testing and improving QA',
  'What is your timeframe from start to finish?',
  'Explain your experience with Agile development environments',
  'Explain your design process',
  'What are some of your favorite projects in your portfolio, and why are they special to you?',
  'What software tools are you most proficient in?',
  'How do you stay current with design trends and industry best practices?',
  "What are some of the key challenges you've seen (and what is your approach for overcoming them) when working on early stage experiences?",
  "Can you share an example of a challenging problem you've faced in a project and how you solved it?",
  'Can you share an experience where you had to quickly learn and adapt to a new technology or approach?',
  'Can you outline your approach to completing this project?',
  'How do you handle revisions or changes in project scope?',
  'Do you have any questions about the job description?',
  'Do you have any questions about the job description?',
];
