services:
  upwork-bidder:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=upwork-bidder
    ports:
      - "5432:5432"
    volumes:
      - upwork-bidder_postgres:/var/lib/postgresql/data
volumes:
  upwork-bidder_postgres:
    driver: local
